version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus${DEMO_NUM}.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${DEMO_NUM}9090:9090"
    networks:
      dashboard:
        ipv4_address: "172.27.${DEMO_NUM:-1}.2"
  grafana:
    image: grafana/grafana:latest
    # volumes:
    #   - ./grafana/config:/etc/grafana
    #   - ./grafana/grafana${DEMO_NUM}.db:/var/lib/grafana/grafana.db
    ports:
      - "${DEMO_NUM}3000:3000"
    depends_on:
      - prometheus
    networks:
      dashboard:
        ipv4_address: "172.27.${DEMO_NUM:-1}.3"
  redis:
    cap_add:
     - sys_resource

    # Build local image based on public redislabs/redis:latest container
    # with netstat wrapper to fix envoy reconfigure issues
    build:
      context: .
      dockerfile: ./Dockerfile
    # OR use internal image which has envoy fix
    # image: redislabs/redis-internal:7.14.0-43.focal
    # once 7.14 is release publically we can just go back to following line
    # image redislabs/redis:latest
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    platform: linux/amd64
    ports:
     - "${DEMO_NUM}6379:6379"
     - "${DEMO_NUM}8070:8070"
     - "${DEMO_NUM}8443:8443"
     - "${DEMO_NUM}9443:9443"
     - "${DEMO_NUM:-1}2000-${DEMO_NUM:-1}2001:12000-12001"
    depends_on:
      - grafana
    networks:
      dashboard:
        ipv4_address: "172.27.${DEMO_NUM:-1}.4"
networks:
  dashboard:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
       -
        subnet: 172.27.${DEMO_NUM:-1}.0/24
        gateway: 172.27.${DEMO_NUM:-1}.1

